### ISSUE TITLE
私服问题

### ISSUE THREAD

**Issue by targerr** [fankay/kaishengit-lab#27]
## 凯哥:这个怎么破 
-    ### 更新公司私服idea 识别不到,eclipse可以
![pom](https://user-images.githubusercontent.com/23501552/30771361-d5cdbfa4-a078-11e7-8c10-cb682b0f027a.png)
-    ### 不优雅的解决方式
![poms](https://user-images.githubusercontent.com/23501552/30771369-edc13b9a-a078-11e7-9c09-b99ff7dc8eb8.png)
# 温馨提示:点击图片看大图

**Comment by fankay** [comment]
有可能是包没有下载完全
